import 'modal_dialog_controller.dart';

class CountryDeliveryReviewMediaDetailModalDialogController extends ModalDialogController {
  CountryDeliveryReviewMediaDetailModalDialogController(super.controllerManager);
}