import '../itemtypelistsubinterceptor/verticalgriditemtypelistsubinterceptor/vertical_grid_item_type_list_sub_interceptor.dart';
import 'list_item_controller_state_wrapper_parameter.dart';

class VerticalListItemControllerStateWrapperParameter extends ListItemControllerStateWrapperParameter {
  VerticalGridPaddingContentSubInterceptorSupportParameter? verticalGridPaddingContentSubInterceptorSupportParameter;

  VerticalListItemControllerStateWrapperParameter({
    required this.verticalGridPaddingContentSubInterceptorSupportParameter
  });
}