// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsCVicIratxXUpeifxcKS7N0oZvj_ey5o',
    appId: '1:151553594780:android:afccd08f09e9f2d5992459',
    messagingSenderId: '151553594780',
    projectId: 'webmasterbagasi',
    databaseURL: 'https://webmasterbagasi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webmasterbagasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT9osKWdU90pJjIsqiUkbdQcC2RkH7FJE',
    appId: '1:151553594780:ios:cc2e427667af7d0d992459',
    messagingSenderId: '151553594780',
    projectId: 'webmasterbagasi',
    databaseURL: 'https://webmasterbagasi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webmasterbagasi.appspot.com',
    iosClientId: '151553594780-8mgsd886fsecg8pu6qv7vrnlhh1vgvg4.apps.googleusercontent.com',
    iosBundleId: 'com.masterbagasi.masterbagasi',
  );
}
